JuliaIO/Tar.jl

src/extract.jl
Got this behavior on Windows, julia 1.3RC4:
```julia
julia> using Tar
[ Info: Precompiling Tar [a4e569a6-e804-4fa4-b0f3-eef7a1d5b13e]
ERROR: LoadError: LoadError: UndefVarError: Cmode_t not defined
```
I noticed that this constant is not defined on Windows:
https://github.com/JuliaLang/julia/blob/dbe50f9787cd056b39917612394eeab339e34406/base/c.jl#L150-L159
=> prevent UndefVarError for Cmode_t on loading package on Windows

src/create.jl
`link` is set to the empty string if it is too long and will be set in the extended header
=> write possibly emptied link to standard header

src/Tar.jl
`out` was not defined, this shoud be the stream itself, as the second argument.
=> fix create to IO

src/create.jl
Make sure we don't hit https://github.com/JuliaPackaging/BinaryBuilder.jl/issues/527. See also https://github.com/JuliaLang/Pkg.jl/pull/1513 which should be the same criterion.
=> create: only look at user exe bit for execuableness

README.md
92% coverage is nothing to hide
Is this package ready to release a first version on the registry, such that other packages can start depending on it?
=> show Travis and Codecov badges in readme

src/extract.jl, test/runtests.jl
I realized that a path should be removed from the links set if it a non-link overwrites a link. This fixes that logic and adds a test that exercises this issue:
- create `path` as a symlink
- overwrite `path` as a directory
- write `path/file` inside of that directory
Previously this triggered the "symlink ovewrite attack" detection since `path` was added to the links set and not removed when the symlink was replaced by a plain directory. Now `path` is removed from the links set when the symlink is replaced by a directory, so the write to `path/file` is allowed.
Admittedly, this is a weird thing for a tarball to do, but since it is safe, we may as well allow it for the sake of consistency.
=> allow write into directory overwriting a symlink

src/Tar.jl, src/extract.jl, src/header.jl, test/runtests.jl
Closes https://github.com/JuliaLang/Tar.jl/issues/14 by adding support for reading and extracting GNU long link and long name extensions. These are non-POSIX, but since they're easy to support and GNU tar is so widely used, we might as well support them. This StackOverflow page has a bit more information about these extensions: https://stackoverflow.com/questions/2078778/what-exactly-is-the-gnu-tar-longlink-trick. It's pretty straightforward: a header entry of type `L` indicates that the data for that entry is the path name of the following standard entry plus a trailing NUL byte; a header entry of type `L` indicates that the data for that entry is the link path of the following standard entry plus a trailing NUL byte.
=> add support for GNU long link and long name extensions

src/Tar.jl
This is still an unofficial option, but it may as well be supported consistently in the API.
=> list: allow passing `raw` option with `tarball::IO`

src/Tar.jl
This is fine on UNIX but may fail on Windows.
=> Windows: close temp handle before trying to delete temp file

README.md, src/Tar.jl
Clarify that if `predicate(path)` is false for a directory, nothing under that directory is included.
=> create docs: clarify predicate behavior on dirs (close #28)

src/Tar.jl, src/create.jl, src/extract.jl
Makes creating a tarball and compressing it with `zstdmt` about 6x
faster (30s vs 5s). Raw `tar` is still about 20% faster, but we'd
probably need https://github.com/JuliaIO/Tar.jl/issues/33 to make
up the difference.
=> Increase default buffer size

src/extract.jl
Also applies to similar logic in git_file_hash. This removes the implicit assumption that the buffer size is a multiple of 512, although it probably should still be, but there's no real reason to require that, so why not make it work generally.
=> read_data: fix premature eof logic

src/create.jl, test/runtests.jl
This changes the canonical sort order that tarballs are created with.
Instead of using the ordering git uses, where entries are sorted by
name but directories are sorted with a trailing `/` appended, this
just sorts by name, full stop. It also changes how directories are
stored in tarballs: it omits the trailing slash at the end of their
path. Since non-empty directories are implicit, this only affects
tarballs that contain empty subdirectories.
=> format change: sort purely by name, no '/' added to dirs

src/Tar.jl
This was painfully slow before due to locking byte I/O.
=> skip(Process): use buffered I/O when skipping process output

README.md, src/Tar.jl, src/create.jl, src/extract.jl, test/runtests.jl
Implements low level `rewrite_tarball` in terms of `read_tarball` and `write_tarball` abstractions, use that to implement `Tar.rewrite` API. In order to support that, previous commits allow an arbitrary driver to generate a correctly constructed canonical tarball without necessarily coming from the filesystem. This abstraction of `write_tarball` may be externally useful (I have a use case in mind, which is what prompted this work) even if it's not an official public API. Having at least two internal users has helped with getting the abstraction right and finding bugs.
=> new API: Tar.rewrite([pred], old, [new])

src/Tar.jl
These utility functions are more generally useful than this; I wanted
to copy them to use them elsewhere but the very specific argument name
`tarball` was inappropriate; this can be any kind of `file`.
=> open_{read,write}: use generic `file` argument name

README.md, src/Tar.jl, src/extract.jl, test/runtests.jl
`Tar.list` with a callback applies the callback to each header instead of returning all of them. Still needs tests and documentation updates.
=> list with callback: iterate instead of listing

src/Tar.jl, test/runtests.jl
Test by no longer explicitly calling `close(io)` after using `Tar.create` to write a tarball: before this change, those tests failed (after fixing them to actually test writing to IO handles in the previous commit) whereas with this change they pass.
This PR also fixes the aforementioned `Tar.create` tests that weren't testing what they were supposed to tests, so if you make the test-only part of the final commit, the tests will actually fail, as they should (since flush is not called on the IO handle).
In the process I made some other minor improvements:
* use `tempname` instead of `mktemp` if the IO handle isn't needed
* `Tar.rewrite`: add two missing arg type combination tests
=> open_write(IO): always flush IO handle

test/runtests.jl, test/setup.jl
This way you can do `include("test/setup.jl")` and then run any of
the testset groups from the main file since they are independent.
=> tests: move setup/helper code to separate file

src/Tar.jl, src/extract.jl
The primary functional change in this PR is that global extended POSIX headers are now propagated to following header entries as specified by the standard. Previously we didn't bother with this since we ignore most extended headers for which this makes sense (atime, charset, gid, gname, hdrcharset, mtime, uid, uname). The headers we do pay attention to—size, path, linkpath—are not ones that it usually makes sense to set in a global header since each entry will typically need it's own value of these.
However, for the ["skeleton" functionality](https://github.com/JuliaIO/Tar.jl/pull/48) I'm considering adding, it would be nice if the skeleton file was a valid tarball where all the files happen to have zero size. But in order to be able to reproduce the original tarball perfectly, we want to …
=> propagate global metadata & relax metadata checking

test/runtests.jl
Previously, this was testing that GNU tar can list a tarball, which,
yes, of course it can. This now tests that it can list a skeleton.
=> tests: actually test that GNU tar can list a skeleton file

Project.toml, src/Tar.jl, test/runtests.jl, test/setup.jl
The new ArgTools package abstracts out the open_{read,write} functionality
we had in here and adds tooling for comprehensive testing. In this first
commit, we leave the functionality of the Tar package unchanged--the same
set of argument types are accepted. In a separate commit, we can unrestrict
this and get support for command arguments and pipelines, for free (and
tests).
=> use ArgTools for read/write args & testing

src/extract.jl, test/runtests.jl
Also add a test case that hits this error path.
=> Fix variable name in `git_file_hash()` error path

Project.toml, src/extract.jl, test/runtests.jl, test/setup.jl
Tar formats pad their inputs with zeros to have all content aligned to
a certain block size; when extracting data, we used a `while` loop to
iterate until we had consumed all non-padded data within the stream,
when we actually needed to iterate until we had consumed all of the
zero-padded data as well.  This was only an issue when the stream
buffering lined up such that a `readbytes!()` call ends with reading all
nonzero content, but not all zero-padding.
To test this, I have added a buffer stream type that allows us to
control the number of bytes returned from a read operation, as well as
allowing it to be randomized, for some simple fuzzing.
=> Fix padding assertion errors

src/extract.jl
Seems like some implementations don't set the magic field to `ustar`. It seems fine to just ignore this field. The checksum field does always seem to be set and will catch input that isn't meant to be a TAR file at all.
=> read: ignore the magic header field (fix #67)

test/runtests.jl, test/setup.jl
Also fix one test that should have used the JLL gtar but was still
checking for the existence of a system tar.
=> tests: make it easier to turn GNU tar tests on/off

test/runtests.jl, test/setup.jl
I don't intend to merge this, I've created it as a brach whose versions of Tar can be [included in Julia as a stdlib](https://github.com/JuliaLang/julia/pull/37763) without needing non-stdlib dependencies for testing. This is a transient solution until we're able to test stdlibs with non-stdlib test dependencies. cc @KristofferC, @staticfloat
=> tests: drop all non-stdlib test dependencies

src/extract.jl
This eliminates 198 invalidations from `using CategoricalArrays`.
=> Fix inference problems in read_header

src/extract.jl, src/header.jl
These two extra patches get things passing on Windows for me.
=> Use `Sys.isexecutable()` on Windows to determine file mode

Project.toml, src/extract.jl, src/header.jl, test/git_tools.jl, test/setup.jl
Unbekownst to me, Windows defaults to files being executable, so we were incorrectly extracting normal files as executables. We didn't detect this because until https://github.com/JuliaLang/julia/pull/35625 we were blind to the executable bit on Windows. With that change, however, we can now tell that we are incorrectly leaving normal files executable. https://github.com/JuliaLang/Pkg.jl/pull/2253 fixes Pkg's GitTools.tree_hash and in the process breaks our tests since they now correctly detect that we are extracting non-executable files incorrectly on Windows. This PR fixes that, making tests pass again with that fix. Failure observed in https://github.com/JuliaLang/julia/pull/38678.
=> Windows file modes: turn executable bits off for plain fails

src/extract.jl
@staticfloat has informed me that on Windows newly created files are neither reliably executable nor non-executable: it depends on the ACL of the directory in which the file is created. So this PR changes the logic for setting permissions to check that the executableness of the file in the tarball and the extracted file match and if not, then use `chmod` to make it so. This logic is the same everywhere, it just happens that on non-Windows platforms files aren't created with execute bits set (I think; if they are, we'll now handle it properly, i.e. by turning them off for non-executable files).
=> Windows extract: always chmod files

src/extract.jl, test/git_tools.jl
See https://github.com/JuliaLang/Pkg.jl/pull/2273. This is a real roller coaster. I would have naively thought that `Sys.isexeccutable` means the same thing as checking the user execute bit, but apparently not. It seems safer to assume that on non-Windows systems files we just created are never executable. This also avoids doing an unneccessary file stat on non-Windows systems.
=> macOS: apparently Sys.isexecutable is not reliable

test/runtests.jl
Before switching to `Tar.jl`, for some time `Pkg.PlatformEngines.package`
produced tarballs with wrong permissions under a weird condition: a directory
had a symlink pointing to it, see
https://github.com/JuliaLang/Pkg.jl/issues/2185 and
https://github.com/JuliaPackaging/Yggdrasil/issues/1969.  This PR adds a
regression test to prevent `Tar.jl` from doing something similarly silly.
Close https://github.com/JuliaLang/Pkg.jl/issues/2185, close https://github.com/JuliaLang/Pkg.jl/pull/2274.
=> Add regression test for permissions in `Tar.create`

src/extract.jl, test/runtests.jl
Windows doesn't give realistic results from `filemode()`, so let's avoid using it to try and pick up `umask`-style environmental information, and just use the mode within the tarball.
=> When extracting, don't use `filemode()` on windows

src/extract.jl, test/runtests.jl
The reason for using `filemode` to read the created mode was to respect the umask or equivalent mechanism for default permissions. Since the umask can only take permissions away, it is always correct to AND the default permissions with the desired permissions, since that will be more constrained than both the default and what the tarball requests.
=> Tar.extract: slight mode improvement

README.md, src/extract.jl
This would require a minor version bump since it changes the way extraction handles permissions: this changes it to ignore the exact permissions in the tarball and only pay attention to whether each file is user-executable and then behave as if the permissions where the git-normlized ones of `0o644` and `0o755`. Unlike the other permission changes, which were bugfixes to deal with `filemode` being unreliable on some platforms, this is a policy change. It's currently a draft since I need to change the docs back to an older version where they claimed this was the behavior even though it actually wasn't at the time.
=> extract: normalize tarball modes (like git)

README.md, src/Tar.jl, src/create.jl, src/extract.jl, src/header.jl, test/runtests.jl
- Allowing the `Tar.list` callback to receive the raw header data (especially in the form of a vector of fields) is highly useful for analyzing wild tarballs. I implemented this when working on adding [support for hard links](https://github.com/JuliaIO/Tar.jl/issues/101) so that I could look at a tarball containing hard links more easily.
- Adding a `Header` method that takes an existing `Header` object and modifies some of its fields is a pattern that's used in various places in the code base which this method makes cleaner and clearer.
- This makes all cases where the end of a tarball is encountered before it is expected throw the same `EOFError` whereas previously some places threw that error while others threw a generic error with a premature end of file message.
- This changes also …
=> miscellaneous fixes and improvements

src/create.jl, src/extract.jl, test/runtests.jl
This fixes three related bugs when processing tarballs where a directory entry appears *after* some contents of that directory. This is unusual since neither command-line `tar` nor `Tar.create` will produce tarballs like this, and I only dicovered the bug when I accidentally modified `Tar.create` to emit directory entries after emiting everything inside of the directory. Each of `extract`, `tree_hash` and `rewrite` did this wrong in slightly different ways previously. Now they all (hopefully) do the right thing, and we test that they each handle a manually generated tarball with this kind of unusual ordering.
=> fix bugs handling unusual tarballs with directory after contents

README.md, src/create.jl, test/runtests.jl, test/setup.jl
Issue #103 points out that omitting directory entries for non-empty directories can confuse some tools that consume tarballs, including docker, which applies overly restrictive permissions to directories which are not explicitly included in a tarball.
This commit changes `Tar.create` and `Tar.rewrite` to produce tarballs which include explicit directory entries for all (non-root) directories. This changes Tar.jl's "canonical format", which is, by design one-to-one with git tree hashes. However, it does not seem like anyone currently depends on that exact reproducibility and it seems worth making this change in order to avoid confusing external consumers of our tarballs.
Closes #103.
=> Tar.create: include entries for non-empty directories

src/Tar.jl, src/create.jl, test/runtests.jl, test/setup.jl
While implementing support for hardlinks, the truncated tarball test was causing problems because it was simply cutting the test tarball in half, which is neither guaranteed to create an ill-formed truncated tarball at all (it is easily possible for half a tarball to be a valid tarball by itself), nor guaranteed to consistently truncate the tarball in the same way on different platforms since we generate somewhat different test tarballs on different platforms (depending on: whether we are able to create hardlinks and what the max file name length is). The fact that this test worked previously was essentially dumb luck.
This change replaces the previous test with systematic tests that various specific truncations of a simple, consistent tarball trigger EOFErrors as expected in all the API …
=> tests: better tests for tarball truncation

README.md, src/Tar.jl, src/create.jl, src/extract.jl, src/header.jl, test/setup.jl
It turns out that implementing hard links is easy: you just copy the hard link target instead of creating the file directly. The tricky part is making sure that a malicious tarball doesn't do something dangerous with a combination of hard links and symlinks, and this can get very tricky indeed. Closes #101.
I'm also including a couple of unrelated helper changes here:
- `Tar.list` with callback: allow passing raw header data — this is useful for analyzing wild tarballs
- `Header(hdr)` constructor with keywords to modify `hdr` — I need to copy a header and this is convenient
=> Support for extracting hard links

src/Tar.jl, src/extract.jl, test/runtests.jl
The `read_data(::iO)` method previously used a single call to `readbytes!` which is incorrect since `readbytes!` only reads as many bytes as is currently available and doesn't block to get more data. This change fixes that bug by using `read!` with a view buffer, which was only added to Base in Julia 1.4, so this also conditionally adds that method to `read!` if necessary.
=> fix read_data bug & use in read_standard_header

src/extract.jl
If we don't do this then reading a tarball from a process and ending early will cause a `SIGPIPE`, which we don't want to do, and which we recently made an error (again) on Julia master.
=> read_standard_header: always keep reading to the end

src/extract.jl, test/runtests.jl, test/setup.jl
This includes two changes to fix https://github.com/JuliaIO/ArgTools.jl/issues/20:
- `Tar.list` now reads to the end of the tarball instead of stopping reading when it hits a zero block
- test sets that expect errors now explicitly read to the end of the tarball inside of the `@arg_test` block
There's also an unrelated change to `make_test_dir` that bit me while making this change.
=> read to the end of tarballs

README.md, src/Tar.jl, src/extract.jl, test/runtests.jl
This adds an option to extract a tarball without using any of the file permissions in the tarball.
I primarily need this on Windows so that I can extract a tarball and have all the extracted files just inherit permissions from the folder where I extract them to.
If this PR is acceptable I'll add a test and docs.
=> Add set_permissions argument

src/extract.jl
These get invalidated by loading Static.jl, specifically the method
```
Base.convert(::Type{T}, ::StaticInt{N}) where {T<:Number,N} = convert(T, N)
```
CC @ChrisRackauckas
=> Fix ~160 invalidations from partially-inferred kwargs to `Header`

src/extract.jl
This fixes dozens of invalidations when loading the InlineStrings package
=> Standardize on String for `link_target`

src/extract.jl
This will probably fail without the new `convert` methods in https://github.com/JuliaLang/julia/pull/44500, so wait until that is merged and we're ready to commit to Julia 1.9.
=> Standardize string types in match call

src/create.jl
I'm new to fixing invalidations, so please help me understand whether I'm doing it correctly.
I ran the following code on Julia v1.8.0:
```julia
julia> using Pkg; Pkg.activate(temp=true); Pkg.add("ArrayInterface")
julia> using SnoopCompileCore
julia> invalidations = @snoopr using ArrayInterface;
julia> using SnoopCompile
julia> length(uinvalidated(invalidations))
1962
julia> trees = invalidation_trees(invalidations);
julia> trees[end-1]
inserting (::Colon)(L::Integer, ::Static.StaticInt{U}) where U in ArrayInterface at /home/hendrik/.julia/packages/ArrayInterface/qyd0m/src/ranges.jl:157 invalidated:
mt_backedges:  1: signature Tuple{Colon, Int64, Any} triggered MethodInstance for InteractiveUtils.recursive_dotcalls!(::Expr, ::Vector{Any}, ::Int64) (0 children)
2: signature Tuple{Colon, …
```
=> hopefully fix invalidations from ArrayInterface.jl

src/create.jl, src/extract.jl
This improves type stability and fixes some invalidations when loading ArrayInterface.jl.
It follows the approach of #112 to cast the optional argument of `readbytes!` to an `Int` and fixes additional invalidations not covered by #138, #139.
I built Julia from the current `release-1.8` branch with
```bash
julia$ git diff release-1.8
diff --git a/stdlib/Tar.version b/stdlib/Tar.version
index b7ee00e5a2..7835dfb18f 100644
--- a/stdlib/Tar.version
+++ b/stdlib/Tar.version
@@ -1,4 +1,4 @@
-TAR_BRANCH = master
-TAR_SHA1 = 0f8a73d5cd4b0c8f1f3c36799c96e9515e9dc595
-TAR_GIT_URL := https://github.com/JuliaIO/Tar.jl.git
-TAR_TAR_URL = https://api.github.com/repos/JuliaIO/Tar.jl/tarball/$1
+TAR_BRANCH = hr/fix_invalidations
+TAR_SHA1 = f63d9034a30171962de52c375572a310e1dffd2c
+TAR_GIT_URL := …
```
=> convert output of `readbytes!` to `Int`

src/extract.jl, test/runtests.jl, test/setup.jl
We have always prevented this for security reasons, but although we have tested that the fancy attacks using symlinks are prevented, we haven't been testing that the basic attack of extracting a relative or absolute  path outside of the tarball is prevented. This adds tests for that. It also factors the common logic for these attack tests into a helper function and tests that `Tar.rewrite` errors in the same way.
=> Test.extract: test that extracting outside of dest directory is an error

src/Tar.jl, src/create.jl, src/extract.jl, test/runtests.jl, test/setup.jl
Check for bad Windows paths prior to extraction; allow check on creation Previously, we didn't bat an eye at extracting paths that are considered bad or illegal on Windows. This explicitly checks for such paths before  attempting extraction on Windows. On all platforms it introduces the `portable` flag for tarball creating operations, which does the same checks and errors if you would have created a tarball that would error   upon extraction on Windows.
=> Check for bad Windows paths prior to extraction; allow check on creation

src/Tar.jl, src/extract.jl
I originally tried to fix this in SHA.jl, but it is more probably more appropriate to fix it here. The problem is summarized here: https://github.com/JuliaCrypto/SHA.jl/pull/88#issuecomment-1516151954
=> minimize impact of invalidations due to uninferred `ctx`

src/extract.jl
I'm usually not a big fan of having overly specific hints in error messages, but basically every time I've seen
```
Error: AssertionError: size == padded_size == 0
```
reported during installation of artifacts the problem was insufficient space on disk.  I think in this case it'd be beneficial to tip to check disk usage.
=> Give hint about possible insufficient storage on error message

src/Tar.jl, src/create.jl, src/extract.jl, test/git_tools.jl, test/runtests.jl
With these changes if you run JET on Julia master, Tar passes:
```jl
julia> import JET; JET.report_package("Tar")
[toplevel-info] virtualized the context of Main (took 0.006 sec)
[toplevel-info] entered into /Users/stefan/dev/Tar/src/Tar.jl
[toplevel-info] entered into /Users/stefan/dev/Tar/src/header.jl
[toplevel-info]  exited from /Users/stefan/dev/Tar/src/header.jl (took 0.022 sec)
[toplevel-info] entered into /Users/stefan/dev/Tar/src/create.jl
[toplevel-info]  exited from /Users/stefan/dev/Tar/src/create.jl (took 0.043 sec)
[toplevel-info] entered into /Users/stefan/dev/Tar/src/extract.jl
[toplevel-info]  exited from /Users/stefan/dev/Tar/src/extract.jl (took 0.069 sec)
[toplevel-info]  exited from /Users/stefan/dev/Tar/src/Tar.jl (took 0.196 sec)
[toplevel-info] analyzing from …
```
=> Fix some issues found by JET

docs/src/index.md, src/Tar.jl, test/runtests.jl
Handles the `Tar` part of https://github.com/JuliaLang/julia/issues/52725.
cc @stevengj
=> Add docstring for Tar module

.github/workflows/ci.yml
Ref: https://discourse.julialang.org/t/psa-new-version-of-codecov-action-requires-additional-setup/109857/1
=> Fix Codecov

src/Tar.jl, test/runtests.jl
Kind of wild that no one complained about this earlier.
=> Accept other string types for all string arguments (fix #179)
